// This file is auto-generated by @hey-api/openapi-ts

export type CompetitionsCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/competitions/create';
};

export type CompetitionsCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type CompetitionsCreateResponse = CompetitionsCreateResponses[keyof CompetitionsCreateResponses];

export type ContractsCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/contracts/';
};

export type ContractsCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContractsCreateResponse = ContractsCreateResponses[keyof ContractsCreateResponses];

export type ContractsCloseData = {
    body?: never;
    path: {
        /**
         * Contract unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/contracts/{id}/close';
};

export type ContractsCloseErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ContractsCloseError = ContractsCloseErrors[keyof ContractsCloseErrors];

export type ContractsCloseResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContractsCloseResponse = ContractsCloseResponses[keyof ContractsCloseResponses];

export type ContractsRenewData = {
    body?: never;
    path: {
        /**
         * Contract unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/contracts/{id}/renew';
};

export type ContractsRenewErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ContractsRenewError = ContractsRenewErrors[keyof ContractsRenewErrors];

export type ContractsRenewResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContractsRenewResponse = ContractsRenewResponses[keyof ContractsRenewResponses];

export type ContractsGetByIdData = {
    body?: never;
    path: {
        /**
         * Contract unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/contracts/{id}';
};

export type ContractsGetByIdErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ContractsGetByIdError = ContractsGetByIdErrors[keyof ContractsGetByIdErrors];

export type ContractsGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContractsGetByIdResponse = ContractsGetByIdResponses[keyof ContractsGetByIdResponses];

export type FacilitiesDeleteData = {
    body?: never;
    path: {
        /**
         * Facility unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/facilities/{id}';
};

export type FacilitiesDeleteErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type FacilitiesDeleteError = FacilitiesDeleteErrors[keyof FacilitiesDeleteErrors];

export type FacilitiesDeleteResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
    };
};

export type FacilitiesDeleteResponse = FacilitiesDeleteResponses[keyof FacilitiesDeleteResponses];

export type FacilitiesGetByIdData = {
    body?: never;
    path: {
        /**
         * Facility unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/facilities/{id}';
};

export type FacilitiesGetByIdErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type FacilitiesGetByIdError = FacilitiesGetByIdErrors[keyof FacilitiesGetByIdErrors];

export type FacilitiesGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FacilitiesGetByIdResponse = FacilitiesGetByIdResponses[keyof FacilitiesGetByIdResponses];

export type FacilitiesUpdateData = {
    body?: never;
    path: {
        /**
         * Facility unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/facilities/{id}';
};

export type FacilitiesUpdateErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type FacilitiesUpdateError = FacilitiesUpdateErrors[keyof FacilitiesUpdateErrors];

export type FacilitiesUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FacilitiesUpdateResponse = FacilitiesUpdateResponses[keyof FacilitiesUpdateResponses];

export type FacilitiesGetBySlugData = {
    body?: never;
    path: {
        /**
         * Facility slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/facilities/slug/{slug}';
};

export type FacilitiesGetBySlugErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type FacilitiesGetBySlugError = FacilitiesGetBySlugErrors[keyof FacilitiesGetBySlugErrors];

export type FacilitiesGetBySlugResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FacilitiesGetBySlugResponse = FacilitiesGetBySlugResponses[keyof FacilitiesGetBySlugResponses];

export type FacilitiesAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/facilities/';
};

export type FacilitiesAllResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FacilitiesAllResponse = FacilitiesAllResponses[keyof FacilitiesAllResponses];

export type FacilitiesCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/facilities/';
};

export type FacilitiesCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FacilitiesCreateResponse = FacilitiesCreateResponses[keyof FacilitiesCreateResponses];

export type FacilitiesFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/facilities/find';
};

export type FacilitiesFindResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FacilitiesFindResponse = FacilitiesFindResponses[keyof FacilitiesFindResponses];

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/';
};

export type GetApiHealthResponses = {
    /**
     * Default Response
     */
    200: {
        status?: string;
        timestamp?: string;
    };
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type NotificationsDeleteData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/notifications/{id}';
};

export type NotificationsDeleteErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type NotificationsDeleteError = NotificationsDeleteErrors[keyof NotificationsDeleteErrors];

export type NotificationsDeleteResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
    };
};

export type NotificationsDeleteResponse = NotificationsDeleteResponses[keyof NotificationsDeleteResponses];

export type NotificationsGetByIdData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/notifications/{id}';
};

export type NotificationsGetByIdErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type NotificationsGetByIdError = NotificationsGetByIdErrors[keyof NotificationsGetByIdErrors];

export type NotificationsGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type NotificationsGetByIdResponse = NotificationsGetByIdResponses[keyof NotificationsGetByIdResponses];

export type NotificationsUpdateData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/notifications/{id}';
};

export type NotificationsUpdateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type NotificationsUpdateError = NotificationsUpdateErrors[keyof NotificationsUpdateErrors];

export type NotificationsUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type NotificationsUpdateResponse = NotificationsUpdateResponses[keyof NotificationsUpdateResponses];

export type NotificationsCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/';
};

export type NotificationsCreateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type NotificationsCreateError = NotificationsCreateErrors[keyof NotificationsCreateErrors];

export type NotificationsCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type NotificationsCreateResponse = NotificationsCreateResponses[keyof NotificationsCreateResponses];

export type NotificationsFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/find';
};

export type NotificationsFindErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type NotificationsFindError = NotificationsFindErrors[keyof NotificationsFindErrors];

export type NotificationsFindResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OffersGetByIdData = {
    body?: never;
    path: {
        /**
         * Offer unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/offers/{id}';
};

export type OffersGetByIdErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type OffersGetByIdError = OffersGetByIdErrors[keyof OffersGetByIdErrors];

export type OffersGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OffersGetByIdResponse = OffersGetByIdResponses[keyof OffersGetByIdResponses];

export type OffersCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/offers/';
};

export type OffersCreateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type OffersCreateError = OffersCreateErrors[keyof OffersCreateErrors];

export type OffersCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OffersCreateResponse = OffersCreateResponses[keyof OffersCreateResponses];

export type OffersProcessData = {
    body?: never;
    path: {
        /**
         * Offer unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/offers/{id}/process';
};

export type OffersProcessErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type OffersProcessError = OffersProcessErrors[keyof OffersProcessErrors];

export type OffersProcessResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OffersProcessResponse = OffersProcessResponses[keyof OffersProcessResponses];

export type OffersFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/offers/find';
};

export type OffersFindResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PlayersDeleteData = {
    body?: never;
    path: {
        /**
         * Player unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/players/{id}';
};

export type PlayersDeleteErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersDeleteError = PlayersDeleteErrors[keyof PlayersDeleteErrors];

export type PlayersDeleteResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersDeleteResponse = PlayersDeleteResponses[keyof PlayersDeleteResponses];

export type PlayersGetByIdData = {
    body?: never;
    path: {
        /**
         * Player unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/players/{id}';
};

export type PlayersGetByIdErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersGetByIdError = PlayersGetByIdErrors[keyof PlayersGetByIdErrors];

export type PlayersGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersGetByIdResponse = PlayersGetByIdResponses[keyof PlayersGetByIdResponses];

export type PlayersUpdateData = {
    body?: never;
    path: {
        /**
         * Player unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/players/{id}';
};

export type PlayersUpdateErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersUpdateError = PlayersUpdateErrors[keyof PlayersUpdateErrors];

export type PlayersUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersUpdateResponse = PlayersUpdateResponses[keyof PlayersUpdateResponses];

export type PlayersGetBySlugData = {
    body?: never;
    path: {
        /**
         * Player slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/players/slug/{slug}';
};

export type PlayersGetBySlugErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersGetBySlugError = PlayersGetBySlugErrors[keyof PlayersGetBySlugErrors];

export type PlayersGetBySlugResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersGetBySlugResponse = PlayersGetBySlugResponses[keyof PlayersGetBySlugResponses];

export type PlayersSearchData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/players/search';
};

export type PlayersSearchErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersSearchError = PlayersSearchErrors[keyof PlayersSearchErrors];

export type PlayersSearchResponses = {
    /**
     * Default Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type PlayersSearchResponse = PlayersSearchResponses[keyof PlayersSearchResponses];

export type PlayersCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/players/';
};

export type PlayersCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersCreateResponse = PlayersCreateResponses[keyof PlayersCreateResponses];

export type PlayersSnapshotData = {
    body?: never;
    path: {
        /**
         * Player unique identifier
         */
        id: number;
    };
    query?: {
        /**
         * Date for the snapshot (YYYY-MM-DD)
         */
        date?: string;
    };
    url: '/api/players/{id}/snapshot';
};

export type PlayersSnapshotErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersSnapshotError = PlayersSnapshotErrors[keyof PlayersSnapshotErrors];

export type PlayersSnapshotResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersSnapshotResponse = PlayersSnapshotResponses[keyof PlayersSnapshotResponses];

export type PlayersUpdateStatisticsData = {
    body?: never;
    path: {
        /**
         * Player unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/players/{id}/updateStatistics';
};

export type PlayersUpdateStatisticsErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersUpdateStatisticsError = PlayersUpdateStatisticsErrors[keyof PlayersUpdateStatisticsErrors];

export type PlayersUpdateStatisticsResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersUpdateStatisticsResponse = PlayersUpdateStatisticsResponses[keyof PlayersUpdateStatisticsResponses];

export type PlayersGetContractsData = {
    body?: never;
    path: {
        /**
         * Player unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/players/{id}/contracts';
};

export type PlayersGetContractsErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersGetContractsError = PlayersGetContractsErrors[keyof PlayersGetContractsErrors];

export type PlayersGetContractsResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersGetContractsResponse = PlayersGetContractsResponses[keyof PlayersGetContractsResponses];

export type PlayersFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/players/find';
};

export type PlayersFindResponses = {
    /**
     * Default Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type PlayersFindResponse = PlayersFindResponses[keyof PlayersFindResponses];

export type PlayersGetPlayerByTmIdData = {
    body?: never;
    path: {
        tmid: string;
    };
    query?: never;
    url: '/api/players/tm/{tmid}';
};

export type PlayersGetPlayerByTmIdErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type PlayersGetPlayerByTmIdError = PlayersGetPlayerByTmIdErrors[keyof PlayersGetPlayerByTmIdErrors];

export type PlayersGetPlayerByTmIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PlayersGetPlayerByTmIdResponse = PlayersGetPlayerByTmIdResponses[keyof PlayersGetPlayerByTmIdResponses];

export type SeasonsDeleteData = {
    body?: never;
    path: {
        /**
         * Season unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/seasons/{id}';
};

export type SeasonsDeleteErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type SeasonsDeleteError = SeasonsDeleteErrors[keyof SeasonsDeleteErrors];

export type SeasonsDeleteResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsDeleteResponse = SeasonsDeleteResponses[keyof SeasonsDeleteResponses];

export type SeasonsGetByIdData = {
    body?: never;
    path: {
        /**
         * Season unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/seasons/{id}';
};

export type SeasonsGetByIdErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type SeasonsGetByIdError = SeasonsGetByIdErrors[keyof SeasonsGetByIdErrors];

export type SeasonsGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsGetByIdResponse = SeasonsGetByIdResponses[keyof SeasonsGetByIdResponses];

export type SeasonsUpdateData = {
    body?: never;
    path: {
        /**
         * Season unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/seasons/{id}';
};

export type SeasonsUpdateErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type SeasonsUpdateError = SeasonsUpdateErrors[keyof SeasonsUpdateErrors];

export type SeasonsUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsUpdateResponse = SeasonsUpdateResponses[keyof SeasonsUpdateResponses];

export type SeasonsGetPhasesData = {
    body?: never;
    path: {
        /**
         * Season unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/seasons/{id}/phases';
};

export type SeasonsGetPhasesErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type SeasonsGetPhasesError = SeasonsGetPhasesErrors[keyof SeasonsGetPhasesErrors];

export type SeasonsGetPhasesResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsGetPhasesResponse = SeasonsGetPhasesResponses[keyof SeasonsGetPhasesResponses];

export type SeasonsAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/seasons/';
};

export type SeasonsAllResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsAllResponse = SeasonsAllResponses[keyof SeasonsAllResponses];

export type SeasonsCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/seasons/';
};

export type SeasonsCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsCreateResponse = SeasonsCreateResponses[keyof SeasonsCreateResponses];

export type SeasonsPhasesCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/seasons/phases';
};

export type SeasonsPhasesCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsPhasesCreateResponse = SeasonsPhasesCreateResponses[keyof SeasonsPhasesCreateResponses];

export type SeasonsPhasesDeleteData = {
    body?: never;
    path: {
        /**
         * Calendar phase unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/seasons/phases/{id}';
};

export type SeasonsPhasesDeleteErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type SeasonsPhasesDeleteError = SeasonsPhasesDeleteErrors[keyof SeasonsPhasesDeleteErrors];

export type SeasonsPhasesDeleteResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsPhasesDeleteResponse = SeasonsPhasesDeleteResponses[keyof SeasonsPhasesDeleteResponses];

export type SeasonsPhasesGetByIdData = {
    body?: never;
    path: {
        /**
         * Calendar phase unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/seasons/phases/{id}';
};

export type SeasonsPhasesGetByIdErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type SeasonsPhasesGetByIdError = SeasonsPhasesGetByIdErrors[keyof SeasonsPhasesGetByIdErrors];

export type SeasonsPhasesGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsPhasesGetByIdResponse = SeasonsPhasesGetByIdResponses[keyof SeasonsPhasesGetByIdResponses];

export type SeasonsPhasesUpdateData = {
    body?: never;
    path: {
        /**
         * Calendar phase unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/seasons/phases/{id}';
};

export type SeasonsPhasesUpdateErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type SeasonsPhasesUpdateError = SeasonsPhasesUpdateErrors[keyof SeasonsPhasesUpdateErrors];

export type SeasonsPhasesUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeasonsPhasesUpdateResponse = SeasonsPhasesUpdateResponses[keyof SeasonsPhasesUpdateResponses];

export type SeasonsFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/seasons/find';
};

export type SeasonsFindResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type StaffDeleteData = {
    body?: never;
    path: {
        /**
         * Staff unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/staff/{id}';
};

export type StaffDeleteErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type StaffDeleteError = StaffDeleteErrors[keyof StaffDeleteErrors];

export type StaffDeleteResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StaffDeleteResponse = StaffDeleteResponses[keyof StaffDeleteResponses];

export type StaffGetByIdData = {
    body?: never;
    path: {
        /**
         * Staff unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/staff/{id}';
};

export type StaffGetByIdErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type StaffGetByIdError = StaffGetByIdErrors[keyof StaffGetByIdErrors];

export type StaffGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StaffGetByIdResponse = StaffGetByIdResponses[keyof StaffGetByIdResponses];

export type StaffUpdateData = {
    body?: never;
    path: {
        /**
         * Staff unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/staff/{id}';
};

export type StaffUpdateErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type StaffUpdateError = StaffUpdateErrors[keyof StaffUpdateErrors];

export type StaffUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StaffUpdateResponse = StaffUpdateResponses[keyof StaffUpdateResponses];

export type StaffGetBySlugData = {
    body?: never;
    path: {
        /**
         * Staff slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/staff/slug/{slug}';
};

export type StaffGetBySlugErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type StaffGetBySlugError = StaffGetBySlugErrors[keyof StaffGetBySlugErrors];

export type StaffGetBySlugResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StaffGetBySlugResponse = StaffGetBySlugResponses[keyof StaffGetBySlugResponses];

export type StaffAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/staff/';
};

export type StaffAllResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StaffAllResponse = StaffAllResponses[keyof StaffAllResponses];

export type StaffCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/staff/';
};

export type StaffCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StaffCreateResponse = StaffCreateResponses[keyof StaffCreateResponses];

export type StaffFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/staff/find';
};

export type StaffFindResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type StaffFindResponse = StaffFindResponses[keyof StaffFindResponses];

export type GetApiStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status/';
};

export type GetApiStatusResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiStatusResponse = GetApiStatusResponses[keyof GetApiStatusResponses];

export type TeamsCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/teams/';
};

export type TeamsCreateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsCreateError = TeamsCreateErrors[keyof TeamsCreateErrors];

export type TeamsCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsCreateResponse = TeamsCreateResponses[keyof TeamsCreateResponses];

export type TeamsDeleteData = {
    body?: never;
    path: {
        /**
         * Team unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/teams/{id}';
};

export type TeamsDeleteErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsDeleteError = TeamsDeleteErrors[keyof TeamsDeleteErrors];

export type TeamsDeleteResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsDeleteResponse = TeamsDeleteResponses[keyof TeamsDeleteResponses];

export type TeamsGetByIdData = {
    body?: never;
    path: {
        /**
         * Team unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/teams/{id}';
};

export type TeamsGetByIdErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsGetByIdError = TeamsGetByIdErrors[keyof TeamsGetByIdErrors];

export type TeamsGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsGetByIdResponse = TeamsGetByIdResponses[keyof TeamsGetByIdResponses];

export type TeamsUpdateData = {
    body?: never;
    path: {
        /**
         * Team unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/teams/{id}';
};

export type TeamsUpdateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsUpdateError = TeamsUpdateErrors[keyof TeamsUpdateErrors];

export type TeamsUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsUpdateResponse = TeamsUpdateResponses[keyof TeamsUpdateResponses];

export type TeamsSnapshotData = {
    body?: never;
    path: {
        /**
         * Team unique identifier
         */
        id: number;
    };
    query?: {
        /**
         * Date for the snapshot (YYYY-MM-DD)
         */
        date?: string;
    };
    url: '/api/teams/{id}/snapshot';
};

export type TeamsSnapshotErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsSnapshotError = TeamsSnapshotErrors[keyof TeamsSnapshotErrors];

export type TeamsSnapshotResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsSnapshotResponse = TeamsSnapshotResponses[keyof TeamsSnapshotResponses];

export type TeamsRosterData = {
    body?: never;
    path: {
        /**
         * Team unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/teams/{id}/roster';
};

export type TeamsRosterErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsRosterError = TeamsRosterErrors[keyof TeamsRosterErrors];

export type TeamsRosterResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsRosterResponse = TeamsRosterResponses[keyof TeamsRosterResponses];

export type TeamsUpdateStatisticsData = {
    body?: never;
    path: {
        /**
         * Team unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/teams/{id}/updateStatistics';
};

export type TeamsUpdateStatisticsErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsUpdateStatisticsError = TeamsUpdateStatisticsErrors[keyof TeamsUpdateStatisticsErrors];

export type TeamsUpdateStatisticsResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsUpdateStatisticsResponse = TeamsUpdateStatisticsResponses[keyof TeamsUpdateStatisticsResponses];

export type TeamsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/teams/stats';
};

export type TeamsStatsErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsStatsError = TeamsStatsErrors[keyof TeamsStatsErrors];

export type TeamsStatsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type TeamsStatsResponse = TeamsStatsResponses[keyof TeamsStatsResponses];

export type TeamsGetBySlugData = {
    body?: never;
    path: {
        /**
         * Team slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/teams/slug/{slug}';
};

export type TeamsGetBySlugErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsGetBySlugError = TeamsGetBySlugErrors[keyof TeamsGetBySlugErrors];

export type TeamsGetBySlugResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsGetBySlugResponse = TeamsGetBySlugResponses[keyof TeamsGetBySlugResponses];

export type TeamsFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/teams/find';
};

export type TeamsFindErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsFindError = TeamsFindErrors[keyof TeamsFindErrors];

export type TeamsFindResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type TeamsGetManagerData = {
    body?: never;
    path: {
        /**
         * Team unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/teams/{id}/manager';
};

export type TeamsGetManagerErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TeamsGetManagerError = TeamsGetManagerErrors[keyof TeamsGetManagerErrors];

export type TeamsGetManagerResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TeamsGetManagerResponse = TeamsGetManagerResponses[keyof TeamsGetManagerResponses];

export type TenantSetupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/setup';
};

export type TenantSetupResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantSetupResponse = TenantSetupResponses[keyof TenantSetupResponses];

export type TenantsGetBySlugData = {
    body?: never;
    path: {
        /**
         * Tenant slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/tenants/slug/{slug}';
};

export type TenantsGetBySlugErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsGetBySlugError = TenantsGetBySlugErrors[keyof TenantsGetBySlugErrors];

export type TenantsGetBySlugResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsGetBySlugResponse = TenantsGetBySlugResponses[keyof TenantsGetBySlugResponses];

export type TenantsDeleteData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}';
};

export type TenantsDeleteErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsDeleteError = TenantsDeleteErrors[keyof TenantsDeleteErrors];

export type TenantsDeleteResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
    };
};

export type TenantsDeleteResponse = TenantsDeleteResponses[keyof TenantsDeleteResponses];

export type TenantsGetByIdData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}';
};

export type TenantsGetByIdErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsGetByIdError = TenantsGetByIdErrors[keyof TenantsGetByIdErrors];

export type TenantsGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsGetByIdResponse = TenantsGetByIdResponses[keyof TenantsGetByIdResponses];

export type TenantsUpdateData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}';
};

export type TenantsUpdateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsUpdateError = TenantsUpdateErrors[keyof TenantsUpdateErrors];

export type TenantsUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsUpdateResponse = TenantsUpdateResponses[keyof TenantsUpdateResponses];

export type TenantsAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/';
};

export type TenantsAllErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsAllError = TenantsAllErrors[keyof TenantsAllErrors];

export type TenantsAllResponses = {
    /**
     * Default Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type TenantsAllResponse = TenantsAllResponses[keyof TenantsAllResponses];

export type TenantsCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/';
};

export type TenantsCreateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsCreateError = TenantsCreateErrors[keyof TenantsCreateErrors];

export type TenantsCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsCreateResponse = TenantsCreateResponses[keyof TenantsCreateResponses];

export type TenantsFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/find';
};

export type TenantsFindErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsFindError = TenantsFindErrors[keyof TenantsFindErrors];

export type TenantsFindResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type TenantsAcceptJoinRequestData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}/acceptJoinRequest';
};

export type TenantsAcceptJoinRequestResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsAcceptJoinRequestResponse = TenantsAcceptJoinRequestResponses[keyof TenantsAcceptJoinRequestResponses];

export type TenantsRefuseJoinRequestData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}/refuseJoinRequest';
};

export type TenantsRefuseJoinRequestErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsRefuseJoinRequestError = TenantsRefuseJoinRequestErrors[keyof TenantsRefuseJoinRequestErrors];

export type TenantsRefuseJoinRequestResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsRefuseJoinRequestResponse = TenantsRefuseJoinRequestResponses[keyof TenantsRefuseJoinRequestResponses];

export type TenantsListJoinRequestsData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}/joinRequests';
};

export type TenantsListJoinRequestsErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsListJoinRequestsError = TenantsListJoinRequestsErrors[keyof TenantsListJoinRequestsErrors];

export type TenantsListJoinRequestsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type TenantsListJoinRequestsResponse = TenantsListJoinRequestsResponses[keyof TenantsListJoinRequestsResponses];

export type TenantsFreeTeamsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tenants/{id}/freeTeams';
};

export type TenantsFreeTeamsErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsFreeTeamsError = TenantsFreeTeamsErrors[keyof TenantsFreeTeamsErrors];

export type TenantsFreeTeamsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type TenantsFreeTeamsResponse = TenantsFreeTeamsResponses[keyof TenantsFreeTeamsResponses];

export type TenantsCurrentSeasonData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}/currentSeason';
};

export type TenantsCurrentSeasonErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsCurrentSeasonError = TenantsCurrentSeasonErrors[keyof TenantsCurrentSeasonErrors];

export type TenantsCurrentSeasonResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsCurrentSeasonResponse = TenantsCurrentSeasonResponses[keyof TenantsCurrentSeasonResponses];

export type TenantsGetConfigurationData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}/configuration';
};

export type TenantsGetConfigurationErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsGetConfigurationError = TenantsGetConfigurationErrors[keyof TenantsGetConfigurationErrors];

export type TenantsGetConfigurationResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsGetConfigurationResponse = TenantsGetConfigurationResponses[keyof TenantsGetConfigurationResponses];

export type TenantsUpdateConfigurationData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}/configuration';
};

export type TenantsUpdateConfigurationErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsUpdateConfigurationError = TenantsUpdateConfigurationErrors[keyof TenantsUpdateConfigurationErrors];

export type TenantsUpdateConfigurationResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsUpdateConfigurationResponse = TenantsUpdateConfigurationResponses[keyof TenantsUpdateConfigurationResponses];

export type TenantsAssignedTeamsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tenants/{id}/assignedTeams';
};

export type TenantsAssignedTeamsErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsAssignedTeamsError = TenantsAssignedTeamsErrors[keyof TenantsAssignedTeamsErrors];

export type TenantsAssignedTeamsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type TenantsAssignedTeamsResponse = TenantsAssignedTeamsResponses[keyof TenantsAssignedTeamsResponses];

export type TenantsGetByTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/token';
};

export type TenantsGetByTokenErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsGetByTokenError = TenantsGetByTokenErrors[keyof TenantsGetByTokenErrors];

export type TenantsGetByTokenResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsGetByTokenResponse = TenantsGetByTokenResponses[keyof TenantsGetByTokenResponses];

export type TenantsGetTokensData = {
    body?: never;
    path: {
        /**
         * Tenant unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/tenants/{id}/tokens';
};

export type TenantsGetTokensErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TenantsGetTokensError = TenantsGetTokensErrors[keyof TenantsGetTokensErrors];

export type TenantsGetTokensResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TenantsGetTokensResponse = TenantsGetTokensResponses[keyof TenantsGetTokensResponses];

export type DeleteApiTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tokens/';
};

export type DeleteApiTokensErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type DeleteApiTokensError = DeleteApiTokensErrors[keyof DeleteApiTokensErrors];

export type DeleteApiTokensResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteApiTokensResponse = DeleteApiTokensResponses[keyof DeleteApiTokensResponses];

export type TokensCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tokens/';
};

export type TokensCreateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TokensCreateError = TokensCreateErrors[keyof TokensCreateErrors];

export type TokensCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TokensCreateResponse = TokensCreateResponses[keyof TokensCreateResponses];

export type ToolsImportPlayersDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools/importPlayersData';
};

export type ToolsImportPlayersDataErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ToolsImportPlayersDataError = ToolsImportPlayersDataErrors[keyof ToolsImportPlayersDataErrors];

export type ToolsImportPlayersDataResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ToolsImportPlayersDataResponse = ToolsImportPlayersDataResponses[keyof ToolsImportPlayersDataResponses];

export type ToolsUpdatePlayersStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools/updatePlayersStatistics';
};

export type ToolsUpdatePlayersStatisticsErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ToolsUpdatePlayersStatisticsError = ToolsUpdatePlayersStatisticsErrors[keyof ToolsUpdatePlayersStatisticsErrors];

export type ToolsUpdatePlayersStatisticsResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ToolsUpdatePlayersStatisticsResponse = ToolsUpdatePlayersStatisticsResponses[keyof ToolsUpdatePlayersStatisticsResponses];

export type ToolsExportPlayersDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools/exportPlayersData';
};

export type ToolsExportPlayersDataErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ToolsExportPlayersDataError = ToolsExportPlayersDataErrors[keyof ToolsExportPlayersDataErrors];

export type ToolsExportPlayersDataResponses = {
    /**
     * Default Response
     */
    200: {
        success?: boolean;
        data?: string;
    };
};

export type ToolsExportPlayersDataResponse = ToolsExportPlayersDataResponses[keyof ToolsExportPlayersDataResponses];

export type ToolsImportPlayersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools/importPlayersList';
};

export type ToolsImportPlayersListErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ToolsImportPlayersListError = ToolsImportPlayersListErrors[keyof ToolsImportPlayersListErrors];

export type ToolsImportPlayersListResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ToolsImportPlayersListResponse = ToolsImportPlayersListResponses[keyof ToolsImportPlayersListResponses];

export type ToolsImportPlayersPesDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools/importPlayersPesData';
};

export type ToolsImportPlayersPesDataErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ToolsImportPlayersPesDataError = ToolsImportPlayersPesDataErrors[keyof ToolsImportPlayersPesDataErrors];

export type ToolsImportPlayersPesDataResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ToolsImportPlayersPesDataResponse = ToolsImportPlayersPesDataResponses[keyof ToolsImportPlayersPesDataResponses];

export type ToolsTmDataGetPlayerData = {
    body?: never;
    path: {
        tmid: string;
    };
    query?: never;
    url: '/api/tools/tmdata/player/{tmid}';
};

export type ToolsTmDataGetPlayerErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ToolsTmDataGetPlayerError = ToolsTmDataGetPlayerErrors[keyof ToolsTmDataGetPlayerErrors];

export type ToolsTmDataGetPlayerResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ToolsTmDataGetPlayerResponse = ToolsTmDataGetPlayerResponses[keyof ToolsTmDataGetPlayerResponses];

export type ToolsTmDataGetTeamData = {
    body?: never;
    path: {
        tmid: string;
    };
    query?: never;
    url: '/api/tools/tmdata/teams/{tmid}';
};

export type ToolsTmDataGetTeamErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ToolsTmDataGetTeamError = ToolsTmDataGetTeamErrors[keyof ToolsTmDataGetTeamErrors];

export type ToolsTmDataGetTeamResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ToolsTmDataGetTeamResponse = ToolsTmDataGetTeamResponses[keyof ToolsTmDataGetTeamResponses];

export type ToolsTmDataSearchData = {
    body?: never;
    path: {
        q: string;
    };
    query?: never;
    url: '/api/tools/tmdata/search';
};

export type ToolsTmDataSearchErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type ToolsTmDataSearchError = ToolsTmDataSearchErrors[keyof ToolsTmDataSearchErrors];

export type ToolsTmDataSearchResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ToolsTmDataSearchResponse = ToolsTmDataSearchResponses[keyof ToolsTmDataSearchResponses];

export type TransactionsInsertData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/transactions/';
};

export type TransactionsInsertErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TransactionsInsertError = TransactionsInsertErrors[keyof TransactionsInsertErrors];

export type TransactionsInsertResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TransactionsInsertResponse = TransactionsInsertResponses[keyof TransactionsInsertResponses];

export type TransactionsFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/transactions/find';
};

export type TransactionsFindErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TransactionsFindError = TransactionsFindErrors[keyof TransactionsFindErrors];

export type TransactionsFindResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type TransactionsGetByIdData = {
    body?: never;
    path: {
        /**
         * Transaction unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/transactions/{id}';
};

export type TransactionsGetByIdErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type TransactionsGetByIdError = TransactionsGetByIdErrors[keyof TransactionsGetByIdErrors];

export type TransactionsGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TransactionsGetByIdResponse = TransactionsGetByIdResponses[keyof TransactionsGetByIdResponses];

export type UsersDeleteData = {
    body?: never;
    path: {
        /**
         * User unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersDeleteErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersDeleteError = UsersDeleteErrors[keyof UsersDeleteErrors];

export type UsersDeleteResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersDeleteResponse = UsersDeleteResponses[keyof UsersDeleteResponses];

export type UsersGetByIdData = {
    body?: never;
    path: {
        /**
         * User unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersGetByIdErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersGetByIdError = UsersGetByIdErrors[keyof UsersGetByIdErrors];

export type UsersGetByIdResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersGetByIdResponse = UsersGetByIdResponses[keyof UsersGetByIdResponses];

export type UsersUpdateData = {
    body?: never;
    path: {
        /**
         * User unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersUpdateErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersUpdateError = UsersUpdateErrors[keyof UsersUpdateErrors];

export type UsersUpdateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersGetByIdentityData = {
    body?: never;
    path: {
        /**
         * External identity ID
         */
        identityId: string;
    };
    query?: never;
    url: '/api/users/identity/{identityId}';
};

export type UsersGetByIdentityErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersGetByIdentityError = UsersGetByIdentityErrors[keyof UsersGetByIdentityErrors];

export type UsersGetByIdentityResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersGetByIdentityResponse = UsersGetByIdentityResponses[keyof UsersGetByIdentityResponses];

export type UsersGetBySlugData = {
    body?: never;
    path: {
        /**
         * User slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/users/slug/{slug}';
};

export type UsersGetBySlugErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersGetBySlugError = UsersGetBySlugErrors[keyof UsersGetBySlugErrors];

export type UsersGetBySlugResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersGetBySlugResponse = UsersGetBySlugResponses[keyof UsersGetBySlugResponses];

export type UsersAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersAllResponses = {
    /**
     * Default Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type UsersAllResponse = UsersAllResponses[keyof UsersAllResponses];

export type UsersCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersCreateResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersFindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/find';
};

export type UsersFindResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type UsersCreateTenantData = {
    body?: never;
    path: {
        /**
         * User unique identifier
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/tenant';
};

export type UsersCreateTenantErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersCreateTenantError = UsersCreateTenantErrors[keyof UsersCreateTenantErrors];

export type UsersCreateTenantResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersCreateTenantResponse = UsersCreateTenantResponses[keyof UsersCreateTenantResponses];

export type UsersJoinRequestsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/joinRequests';
};

export type UsersJoinRequestsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type UsersJoinTenantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/joinTenant';
};

export type UsersJoinTenantErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
    /**
     * Default Response
     */
    500: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersJoinTenantError = UsersJoinTenantErrors[keyof UsersJoinTenantErrors];

export type UsersJoinTenantResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type UsersGetTeamsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/teams';
};

export type UsersGetTeamsErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersGetTeamsError = UsersGetTeamsErrors[keyof UsersGetTeamsErrors];

export type UsersGetTeamsResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersGetTeamsResponse = UsersGetTeamsResponses[keyof UsersGetTeamsResponses];

export type UsersGetTenantsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/tenants';
};

export type UsersGetTenantsErrors = {
    /**
     * Default Response
     */
    404: {
        /**
         * Status code
         */
        statusCode?: number;
        /**
         * Error message
         */
        message?: string;
        /**
         * Short rror message
         */
        error?: string;
    };
};

export type UsersGetTenantsError = UsersGetTenantsErrors[keyof UsersGetTenantsErrors];

export type UsersGetTenantsResponses = {
    /**
     * Generic JSON response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UsersGetTenantsResponse = UsersGetTenantsResponses[keyof UsersGetTenantsResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};